dataset:
  header: label,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26
  select_indexs: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
  select_defs: F,I,I,I,I,I,I,I,I,I,I,I,I,I,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S
  label_index: 0
  batch_size: 512
  skip_head_lines: 0
  field_delim: "\t"
  na_value: ""
features:
  sparse_features:
    - name: C1
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C2
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C3
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C4
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C5
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C6
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C7
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C8
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C9
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C10
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C11
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C12
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C13
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C14
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C15
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C16
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C17
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C18
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C19
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C20
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C21
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C22
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C23
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C24
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C25
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
    - name: C26
      input_length: 1
      hash_bucket_size: 10000
      embedding_dim: 10
  dense_features:
    - name: I1
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I2
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I3
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I4
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I5
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I6
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I7
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I8
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I9
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I10
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I11
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I12
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10
    - name: I13
      boundaries: 0,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000
      default: -1
      norm: null
      embedding_dim: 10